name: swd_mobie_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  # Đã sửa lại dải SDK cho đúng
  sdk: ^3.9.0

# Đã sửa lỗi thụt lề nghiêm trọng ở đây
dependencies:
  flutter:
    sdk: flutter

  # 1. Cho việc đăng nhập Google native
  google_sign_in: ^6.1.6

  # 2. Để gọi API (giống axios/fetch)
  http: ^1.2.1

  # 3. Để quản lý trạng thái (ai đang login, đã login chưa)
  provider: ^6.1.2

  # 4. Để lưu trữ token (JWT) an toàn
  flutter_secure_storage: ^9.1.1

  # 5. Cốt lõi của Clean Architecture (xử lý lỗi)
  dartz: ^0.10.1

  # 6. So sánh các đối tượng
  equatable: ^2.0.5
  
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0

  google_fonts: ^6.3.2

  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Đã sửa lại phiên bản lints cho chuẩn hơn
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/google_logo.png