// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzovV9mqdh6aQub5_k5_QdZbGTY3qOEJk',
    appId: '1:161293462080:web:8de5b478f58dea3b9dcda5',
    messagingSenderId: '161293462080',
    projectId: 'oauth2-event-flower-exchange',
    authDomain: 'oauth2-event-flower-exchange.firebaseapp.com',
    storageBucket: 'oauth2-event-flower-exchange.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4lctlxLuxqPCefZAVyXOfMKSG7We77ss',
    appId: '1:161293462080:android:1401a4a7c0496bce9dcda5',
    messagingSenderId: '161293462080',
    projectId: 'oauth2-event-flower-exchange',
    storageBucket: 'oauth2-event-flower-exchange.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUnG3s6U97S6TuWe6qPQ7OVnsWDZf-uFk',
    appId: '1:161293462080:ios:5cd2270c8145fe4d9dcda5',
    messagingSenderId: '161293462080',
    projectId: 'oauth2-event-flower-exchange',
    storageBucket: 'oauth2-event-flower-exchange.firebasestorage.app',
    androidClientId: '161293462080-l22unsdi9ib261kt4u4igotao8ile0gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.swdMobieFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUnG3s6U97S6TuWe6qPQ7OVnsWDZf-uFk',
    appId: '1:161293462080:ios:5cd2270c8145fe4d9dcda5',
    messagingSenderId: '161293462080',
    projectId: 'oauth2-event-flower-exchange',
    storageBucket: 'oauth2-event-flower-exchange.firebasestorage.app',
    androidClientId: '161293462080-l22unsdi9ib261kt4u4igotao8ile0gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.swdMobieFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzovV9mqdh6aQub5_k5_QdZbGTY3qOEJk',
    appId: '1:161293462080:web:5cc3dfd91388db639dcda5',
    messagingSenderId: '161293462080',
    projectId: 'oauth2-event-flower-exchange',
    authDomain: 'oauth2-event-flower-exchange.firebaseapp.com',
    storageBucket: 'oauth2-event-flower-exchange.firebasestorage.app',
  );
}
